<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return array
     */
    public function myFindBy($id)
    {
        $qb = $this->createQueryBuilder('a')
        ->where('a.id > :id')
        ->setParameter('id', $id)
        ->setMaxResults(9);

        return $qb->getQuery()->getResult();
    }
}
