<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNumberOfArticles()
    {
        $sql = 'SELECT count(id) AS nb_articles from article';
        try {
            $stmt = $this->_em->getConnection()->query($sql);
            $r = $stmt->fetch();
            $stmt->closeCursor();
            return $r;
        } catch (\Exception $exception) {
            return null;
        }
    }

    /**
     * @param $id
     * @return array
     */
    public function myFindBy($id)
    {
        $qb = $this->createQueryBuilder('a')
        ->where('a.id > :id')
        ->setParameter('id', $id)
        ->setMaxResults(9);

        return $qb->getQuery()->getResult();
    }

    /**
     * Function to get the number of articles having the same slug
     * If one or more, must change the slug end value (-2, -3, ...-n)
     * @param $slug
     * @return array
     */
    public function myFindBySlug($slug)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('count(a.id) as count_same_slug')
            ->where('a.slug LIKE :slug')
            ->setParameter('slug', "$slug%");

        return $qb->getQuery()->getResult();
    }
}
