<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Article;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAllCategories()
    {
        return $this->createQueryBuilder('a')
            ->innerJoin("a.articles", "articles")
            ->where("articles.id is not null")
            ->getQuery()->getResult();
    }
}
