<?php

namespace AppBundle\Repository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()
    {
        return $this->_em->getConnection()
            ->fetchAll('SELECT token, email FROM newsletter');
    }
}
