<?php

namespace AppBundle\Repository;

/**
 * StatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindBy($type, $bot, $start, $end)
    {
        $dbh = $this->_em->getConnection();
        $sql = "SELECT * FROM statistic WHERE type='$type'";
        if (!empty($bot)) {
            $sql .= " AND bot='$bot'";
        }

        if (!empty($start)) {
            $sql .= " AND date >= '$start 00:00:00'";
        }

        if (!empty($end)) {
            $sql .= " AND date <= '$end 23:59:59'";
        }
        $sth = $dbh->prepare($sql);
        $sth->execute();
        return $sth->fetchAll();
    }
}
