AppBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
        message:
            type: text
            nullable: false
        date:
            type: datetime
        token:
            type: string
            length: 255
            nullable: false
    lifecycleCallbacks: {  }
