AppBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        src:
            type: string
            length: 255
        title:
            type: string
            length: 255

    manyToOne:
        article:
            targetEntity: AppBundle\Entity\Article
            inversedBy: images

    lifecycleCallbacks: {  }
