AppBundle\Entity\Statistic:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\StatisticRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        data:
            type: string
            length: 255
        type:
            type: string
        bot:
            type: boolean
    lifecycleCallbacks: {  }
